var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var del = require('del');
var swallowError = require('./helpers/swallow-error');

/**
 * Compile less files
 *
 * Options:
 *   --production: Optimize final css.
 */
gulp.task('styles', function () {
  return gulp.src('./less/global.less')
    .pipe($.less().on('error', swallowError))
    .pipe($.autoprefixer({ browsers: ['last 1 versions'] }))
    .pipe($.util.env.production ? $.csso() : $.util.noop())
    .pipe(gulp.dest('./public/css'));
});

/**
 * Watch file change event on save and compile css file.
 */
gulp.task('styles:watch', ['styles'], function () {
  gulp.watch('./less/**/*.less', ['styles']);
});

/**
 * Clean up css files generated by gulp.
 */
gulp.task('styles:clean', function (done) {
  del(['./css/*.css'], done);
});
